Updated settings labels
PMKS-Web/PMKSWeb pull request #148
Opened 2023-07-25 23:21 UTC by AlexG1031

Have English (in) instead of just English and change Degree and Radian to degree (0) and radian (C)

2023-07-26 02:38 UTC, rkprad commented
add parenthesis 
degree ( )
radian ( )

2023-07-27 01:39 UTC, KohmeiK requested changes
<img width="426" alt="Screenshot 2023-07-26 at 9 37 23 PM" src="https://github.com/PMKS-Web/PMKSWeb/assets/19924289/77e2540f-900c-4a99-9c42-b27ab9dcf2ac">

Discussing with Alex, notes:
1. c for radian? 
2. Also white space around letters (for global units)

2023-08-08 00:52 UTC, KohmeiK commented
Change radian to rad
Get rid of 'c' for degrees
- I will fix padding on the global unit buttons @KohmeiK

2023-08-25 02:02 UTC, KohmeiK approved these changes

2023-08-25 02:02 UTC, merged